version: '3.4'
services:
  test_task_rest_api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.local
      args:
        DB_CONNECTION: "postgresql://postgres:secret@db:5432/postgres"
        MODE: "TEST"
    entrypoint: >
      sh -c "sleep 5 && make test"
    volumes:
      - ../:/app/
    environment:
      - PYTHONPATH=/app/task_rest_api
    links:
      - "db:db"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"
    expose:
      - "5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  task_rest_api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.local
      args:
        DB_CONNECTION: "postgresql://postgres:mysecretpassword@db:5432/postgres"
        MODE: "TEST"
    entrypoint: >
      sh -c "sleep 5 && python ./task_rest_api/main.py"
    volumes:
      - ../:/app/
    environment:
      - PYTHONPATH=/app/task_rest_api
    ports:
      - "8080:8080"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/api/v1/version"
        ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - "db:db"
    depends_on:
      - db
